### ISSUE TITLE
YAML file format

### ISSUE THREAD

**Issue by sindresorhus** [editorconfig/editorconfig#78]
I think we should add support for an additional format or replace the current one. I don't really like the INI format and YAML is both flexible and minimalistic in its syntax, while being widely used and standardized.

Example:

``` yaml
'*':
  end_of_line: lf
  insert_final_newline: true
```
